# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media_info.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'media_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10media_info.proto\"\x9c\x01\n\x0cVideoSummary\x12\r\n\x05\x63odec\x18\x01 \x01(\t\x12\x11\n\tbit_depth\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0b\n\x03hdr\x18\x05 \x01(\t\x12\r\n\x05is_3d\x18\x06 \x01(\x08\x12\x1f\n\x17has_hardcoded_subtitles\x18\x07 \x01(\x08\x12\x0e\n\x06source\x18\x08 \x01(\t\"\x89\x01\n\x0c\x41udioSummary\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x12\n\nformat_tag\x18\x02 \x01(\t\x12\x14\n\x0c\x63hannels_tag\x18\x03 \x01(\t\x12\x15\n\ris_commentary\x18\x04 \x01(\x08\x12\x16\n\x0eis_descriptive\x18\x05 \x01(\x08\x12\x0e\n\x06source\x18\x06 \x01(\t\"S\n\x0fSubtitleSummary\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x0e\n\x06is_sdh\x18\x03 \x01(\x08\x12\x0e\n\x06source\x18\x04 \x01(\t\"\xed\x03\n\x10MediaInfoSummary\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07imdb_id\x18\x02 \x01(\t\x12\x0f\n\x07tmdb_id\x18\x03 \x01(\t\x12\x11\n\tunique_id\x18\x04 \x01(\t\x12\x14\n\x0ctorrent_hash\x18\x05 \x01(\t\x12\x0f\n\x07\x65\x64ition\x18\x06 \x01(\t\x12\r\n\x05group\x18\x07 \x01(\t\x12\x0f\n\x07quality\x18\x08 \x01(\t\x12\x11\n\tcontainer\x18\t \x01(\t\x12\x0c\n\x04size\x18\n \x01(\x03\x12\x0c\n\x04site\x18\x0b \x01(\t\x12\x0f\n\x07network\x18\x0c \x01(\t\x12\x10\n\x08\x65xtended\x18\r \x01(\x08\x12\x12\n\nuncensored\x18\x0e \x01(\x08\x12\x10\n\x08upscaled\x18\x0f \x01(\x08\x12\x15\n\rseason_number\x18\x10 \x01(\x05\x12\x16\n\x0e\x65pisode_number\x18\x11 \x01(\x05\x12\x16\n\x0e\x65pisode_string\x18\x12 \x01(\t\x12\x1a\n\x12torrent_file_index\x18\x13 \x01(\x05\x12#\n\x0cvideo_tracks\x18\x14 \x03(\x0b\x32\r.VideoSummary\x12#\n\x0c\x61udio_tracks\x18\x15 \x03(\x0b\x32\r.AudioSummary\x12)\n\x0fsubtitle_tracks\x18\x16 \x03(\x0b\x32\x10.SubtitleSummaryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOSUMMARY']._serialized_start=21
  _globals['_VIDEOSUMMARY']._serialized_end=177
  _globals['_AUDIOSUMMARY']._serialized_start=180
  _globals['_AUDIOSUMMARY']._serialized_end=317
  _globals['_SUBTITLESUMMARY']._serialized_start=319
  _globals['_SUBTITLESUMMARY']._serialized_end=402
  _globals['_MEDIAINFOSUMMARY']._serialized_start=405
  _globals['_MEDIAINFOSUMMARY']._serialized_end=898
# @@protoc_insertion_point(module_scope)
